defaults: &defaults
  amenity_categories:
    laundry: 1
    fridge: 2
    tv: 3
    ac: 4
    water_heater: 5
    net: 6
    local_channel: 7
    gas: 8
  furniture_categories:
    bed: 1
    closet: 2
    sofa: 3
    desk: 4
    chair: 5
    cook_ware: 6
    bedding: 7
  extra_fee_categories:
    security_fee: 1
    clean_fee: 2
    local_channel_fee: 3
    net_fee: 4
    water_fee: 5
    electricity_fee: 6
    gas_fee: 7
  house_type_categories:
    family: 1
    multi_rooms: 2
  gender_categories:
    female_only: 2
    male_only: 1
    both: 3
  public_facility_categories:
    security: 1
    elevator: 2
    garbage: 3
    disabled: 4
  rule_categories:
    family: 1
    foreigner: 2
    pet: 3
    cooking: 4
  personal_parking_lot_categories:
    zero: 1
    one: 2
    two: 3
    two_plus: 4

development:
  <<: *defaults

test:
  <<: *defaults
# instead read values from the environment.
production:
  <<: *defaults