defaults: &defaults
  amenity_categories:
    laundry: 1
    fridge: 2
    tv: 3
    ac: 4
    water_heater: 5
    net: 6
    local_channel: 7
    gas: 8
  furniture_categories:
    bed: 1
    closet: 2
    sofa: 3
    desk: 4
    chair: 5
    cook_ware: 6
    bedding: 7
  extra_fee_categories:
    security_fee: 1
    clean_fee: 2
    local_channel_fee: 3
    net_fee: 4
    water_fee: 5
    electricity_fee: 6
    gas_fee: 7
  house_type_categories:
    family: 1
    multi_rooms: 2
  gender_categories:
    female_only: 2
    male_only: 1
    both: 3
  public_facility_categories:
    security: 1
    elevator: 2
    garbage: 3
    disabled: 4
  rule_categories:
    family: 1
    pet: 2
    cooking: 3
  personal_parking_lot_categories:
    zero: 0
    one: 1
    two: 2
    two_plus: 3
  safety_categories:
    fog: 1
    extinguisher: 2
    co_sensor: 3
    medicine_bag: 4
  foreigner_categories:
    good: 1
    bad: 2
  english_categories:
    great: 1
    normal: 2
    bad: 3
  special_floor_categories:
    none: 0
    basement: 1
    rooftop: 2
    whole_building: 3
  direction_categories:
    north: 1
    east: 2
    west: 3
    south: 4


development:
  <<: *defaults

test:
  <<: *defaults
# instead read values from the environment.
production:
  <<: *defaults