defaults: &defaults
  school_categories:
    Taiwan_University : 1
    Chengchi_University : 2
    Shih_Hsin_University : 3
    Taipei_Education_University : 4
    Taiwan_University_of_Science_and_Technology : 5
    Teacher_University : 6
    Taipei_Medical_University : 7

development:
  <<: *defaults

test:
  <<: *defaults
# instead read values from the environment.
production:
  <<: *defaults