defaults: &defaults
  school_categories:
    National_Taiwan_University : 1
    National_TsingHua_University : 2
    National_ChiaoTung_University : 3
    National_Chengchi_University : 4

development:
  <<: *defaults

test:
  <<: *defaults
# instead read values from the environment.
production:
  <<: *defaults